# Generated by Django 6.0 on 2026-01-29 19:17

import Clinica_Sorriso.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
                ('ddi', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('quantidade_atual', models.PositiveIntegerField(default=0)),
                ('quantidade_ideal', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DadosDaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clinica', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_comunicacoes', models.CharField(blank=True, max_length=30, null=True)),
                ('responsavel_clinica', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinica/logos/')),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('fuso_horario', models.CharField(blank=True, choices=[('ND', 'Nordeste'), ('NE', 'Norte'), ('CO', 'Centro-Oeste'), ('SD', 'Sudeste'), ('SL', 'Sul'), ('NI', 'Não informado')], default='NI', max_length=2, null=True)),
                ('emitir_recibo_em_nome_de', models.CharField(choices=[('CLINICA', 'Clínica'), ('DENTISTA', 'Dentista'), ('NI', 'Não informado')], default='NI', max_length=20)),
                ('email_clinica', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=128, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('NI', 'Não informado')], default='NI', max_length=2, null=True)),
                ('codigo_pais_celular_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinicas_celular', to='Clinica_Sorriso.pais')),
                ('codigo_pais_telefone_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinicas_telefone', to='Clinica_Sorriso.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=Clinica_Sorriso.models.caminho_foto_usuario)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não informado')], default='N', max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('NI', 'Não informado')], default='NI', max_length=2, null=True)),
                ('codigo_pais_telefone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telefone_pais', to='Clinica_Sorriso.pais')),
                ('codigo_pais_whatsapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_pais', to='Clinica_Sorriso.pais')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DentistaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conselho_tipo', models.CharField(choices=[('CRM', 'CRM'), ('CRO', 'CRO'), ('NI', 'Não informado')], default='NI', max_length=3)),
                ('numero_conselho', models.CharField(blank=True, max_length=50, null=True)),
                ('uf_conselho', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('NI', 'Não informado')], default='NI', max_length=2)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinica_Sorriso.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Clinica_Sorriso.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='Clinica_Sorriso.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='RetiradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_retirada', models.PositiveIntegerField()),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiradas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='Clinica_Sorriso.produtoestoque')),
                ('retirado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiradas_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
