# Generated by Django 6.0 on 2026-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0003_alter_agendamento_paciente_alter_paciente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno')], default='consulta', max_length=20),
        ),
    ]
