# Generated by Django 6.0 on 2026-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0004_agendamento_status_agendamento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado'), ('retorno', 'Retorno')], default='pendente', max_length=20),
        ),
    ]
