# Generated by Django 6.0 on 2026-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0005_transacao_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='caixa',
            field=models.CharField(choices=[('clinica', 'Clínica'), ('banco', 'Conta do banco')], default='clinica', max_length=20),
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(blank=True, choices=[('taxas', 'Taxas e Boletos'), ('outras', 'Outras'), ('materiais', 'Materiais Odontológicos'), ('laboratorios', 'Laboratórios'), ('infraestrutura', 'Infraestrutura'), ('encargos', 'Encargos de Funcionários'), ('bancarias', 'Despesas Bancárias'), ('custo_fixo', 'Custo fixo'), ('contabilidade', 'Contabilidade'), ('comissoes', 'Comissões')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='com_recibo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='meio_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('credito_maquininha', 'Crédito Maquininha'), ('credito', 'Crédito'), ('debito_maquininha', 'Débito Maquininha'), ('debito', 'Débito'), ('pix', 'Pix'), ('transferencia', 'Transferência'), ('boleto', 'Boleto')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
