# Generated by Django 6.0 on 2026-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0008_alter_transacao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='meio_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('credito_maquininha', 'Crédito Maquininha'), ('credito', 'Crédito'), ('debito_maquininha', 'Débito Maquininha'), ('debito', 'Débito'), ('pix', 'Pix'), ('transferencia', 'Transferência'), ('boleto', 'Boleto'), ('cheque', 'Cheque')], max_length=50, null=True),
        ),
    ]
