# Generated by Django 6.0 on 2026-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0010_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
