# Generated by Django 6.0 on 2026-02-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0011_alter_plano_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='Clinica_Sorriso.plano'),
        ),
    ]
