# Generated by Django 6.0 on 2026-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0014_pagamentocomissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='paciente_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
