# Generated by Django 6.0.3 on 2026-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0015_transacao_paciente_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Etiqueta')),
                ('cor', models.CharField(default='#28a745', max_length=7, verbose_name='Código Hex da Cor')),
            ],
        ),
    ]
