# Generated by Django 6.0.3 on 2026-07-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0016_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='Clinica_Sorriso.etiqueta', verbose_name='Etiqueta'),
        ),
    ]
