# Generated by Django 6.0.3 on 2026-07-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0017_agendamento_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompromissoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('data_fim', models.DateField()),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('dia_inteiro', models.BooleanField(default=False)),
                ('repetir', models.BooleanField(default=False)),
                ('tipo_repeticao', models.CharField(blank=True, choices=[('todos_os_dias', 'Todos os dias'), ('semanalmente', 'Semanalmente'), ('quinzenalmente', 'Quinzenalmente'), ('mensalmente', 'Mensalmente'), ('anualmente', 'Anualmente')], max_length=30, null=True)),
                ('terminar_repeticao', models.CharField(choices=[('nunca', 'Nunca'), ('data_especifica', 'Data específica')], default='nunca', max_length=30)),
                ('data_fim_repeticao', models.DateField(blank=True, null=True)),
                ('disponibilidade', models.CharField(choices=[('ocupado', 'Ocupado'), ('disponivel', 'Disponível')], default='ocupado', max_length=20)),
                ('privacidade', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público')], default='privado', max_length=20)),
                ('alerta', models.CharField(choices=[('sem_alerta', 'Sem alerta'), ('1_minuto', '1 minuto antes'), ('5_minutos', '5 minutos antes'), ('30_minutos', '30 minutos antes'), ('1_hora', '1 hora antes'), ('1_dia', '1 dia antes'), ('personalizar', 'Personalizar')], default='sem_alerta', max_length=30)),
                ('alerta_quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('alerta_unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to='Clinica_Sorriso.profissional')),
            ],
        ),
    ]
