# Generated by Django 6.0.3 on 2026-07-09 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0018_compromissoagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncaixeAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desejada', models.DateField(blank=True, null=True, verbose_name='Data desejada')),
                ('qualquer_data', models.BooleanField(default=False, verbose_name='Qualquer data')),
                ('turno', models.CharField(blank=True, choices=[('', 'Qualquer turno'), ('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='', max_length=20, verbose_name='Turno desejado')),
                ('plano', models.CharField(blank=True, default='Particular', max_length=100, verbose_name='Plano')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('urgente', models.BooleanField(default=False, verbose_name='Encaixe urgente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaixes_agenda', to='Clinica_Sorriso.etiqueta', verbose_name='Rótulo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaixes_agenda', to='Clinica_Sorriso.paciente', verbose_name='Paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaixes_agenda', to='Clinica_Sorriso.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Encaixe',
                'verbose_name_plural': 'Encaixes',
                'ordering': ['-urgente', 'data_desejada', '-criado_em'],
            },
        ),
    ]
