# Generated by Django 6.0.3 on 2026-07-09 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica_Sorriso', '0019_encaixeagenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_retorno', models.CharField(choices=[('data_especifica', 'Data específica'), ('7_dias', 'Em 7 dias'), ('15_dias', 'Em 15 dias'), ('30_dias', 'Em 30 dias'), ('3_meses', 'Em 3 meses'), ('6_meses', 'Em 6 meses')], default='data_especifica', max_length=30, verbose_name='Retornar em')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data aproximada para retorno')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo do retorno')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_retorno', to='Clinica_Sorriso.paciente', verbose_name='Paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_retorno', to='Clinica_Sorriso.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Alerta de retorno',
                'verbose_name_plural': 'Alertas de retorno',
                'ordering': ['data_retorno', '-criado_em'],
            },
        ),
    ]
